package android.car.oem;

import static android.car.feature.Flags.FLAG_OEM_VEHICLE_PROPERTY;
import android.annotation.SuppressLint;
import android.annotation.FlaggedApi;

public final class OemPermissions {

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_AVERAGE_SPEED_READ = "android.car.permission.oem.AVERAGE_SPEED_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CARGO_VOLUME_READ = "android.car.permission.oem.CARGO_VOLUME_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURB_WEIGHT_READ = "android.car.permission.oem.CURB_WEIGHT_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_ALTITUDE_READ = "android.car.permission.oem.CURRENT_LOCATION_ALTITUDE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_GNSSRECEIVER_FIX_TYPE_READ = "android.car.permission.oem.CURRENT_LOCATION_GNSSRECEIVER_FIX_TYPE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_X_READ = "android.car.permission.oem.CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_X_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Y_READ = "android.car.permission.oem.CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Y_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Z_READ = "android.car.permission.oem.CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Z_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_HEADING_READ = "android.car.permission.oem.CURRENT_LOCATION_HEADING_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_HORIZONTAL_ACCURACY_READ = "android.car.permission.oem.CURRENT_LOCATION_HORIZONTAL_ACCURACY_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_LATITUDE_READ = "android.car.permission.oem.CURRENT_LOCATION_LATITUDE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_LONGITUDE_READ = "android.car.permission.oem.CURRENT_LOCATION_LONGITUDE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_TIMESTAMP_READ = "android.car.permission.oem.CURRENT_LOCATION_TIMESTAMP_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_LOCATION_VERTICAL_ACCURACY_READ = "android.car.permission.oem.CURRENT_LOCATION_VERTICAL_ACCURACY_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_CURRENT_OVERALL_WEIGHT_READ = "android.car.permission.oem.CURRENT_OVERALL_WEIGHT_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_EMISSIONS_CO2_READ = "android.car.permission.oem.EMISSIONS_CO2_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_GROSS_WEIGHT_READ = "android.car.permission.oem.GROSS_WEIGHT_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_HEIGHT_READ = "android.car.permission.oem.HEIGHT_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_IS_BROKEN_DOWN_READ = "android.car.permission.oem.IS_BROKEN_DOWN_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_IS_MOVING_READ = "android.car.permission.oem.IS_MOVING_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_LENGTH_READ = "android.car.permission.oem.LENGTH_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_LOW_VOLTAGE_SYSTEM_STATE_READ = "android.car.permission.oem.LOW_VOLTAGE_SYSTEM_STATE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_MAX_TOW_BALL_WEIGHT_READ = "android.car.permission.oem.MAX_TOW_BALL_WEIGHT_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_MAX_TOW_WEIGHT_READ = "android.car.permission.oem.MAX_TOW_WEIGHT_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_ACCUMULATED_BRAKING_ENERGY_READ = "android.car.permission.oem.POWERTRAIN_ACCUMULATED_BRAKING_ENERGY_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_LEVEL_READ = "android.car.permission.oem.POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_LEVEL_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_TEMPERATURE_READ = "android.car.permission.oem.POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_TEMPERATURE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_CAPACITY_READ = "android.car.permission.oem.POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_CAPACITY_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_LEVEL_READ = "android.car.permission.oem.POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_LEVEL_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_TEMPERATURE_READ = "android.car.permission.oem.POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_TEMPERATURE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_COMBUSTION_ENGINE_IS_RUNNING_READ = "android.car.permission.oem.POWERTRAIN_COMBUSTION_ENGINE_IS_RUNNING_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_COMBUSTION_ENGINE_SPEED_READ = "android.car.permission.oem.POWERTRAIN_COMBUSTION_ENGINE_SPEED_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_ABSOLUTE_LEVEL_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_ABSOLUTE_LEVEL_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_AVERAGE_CONSUMPTION_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_AVERAGE_CONSUMPTION_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_LAST_REFUEL_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_LAST_REFUEL_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_START_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_START_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_HYBRID_TYPE_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_HYBRID_TYPE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_INSTANT_CONSUMPTION_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_INSTANT_CONSUMPTION_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_IS_ENGINE_STOP_START_ENABLED_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_IS_ENGINE_STOP_START_ENABLED_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_LEVEL_LOW_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_IS_FUEL_LEVEL_LOW_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_WRITE = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_WRITE";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_RANGE_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_RANGE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_REFUEL_PORT_POSITION_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_REFUEL_PORT_POSITION_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_RELATIVE_LEVEL_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_RELATIVE_LEVEL_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_TYPES_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_TYPES_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_TANK_CAPACITY_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_TANK_CAPACITY_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_FUEL_SYSTEM_TIME_REMAINING_READ = "android.car.permission.oem.POWERTRAIN_FUEL_SYSTEM_TIME_REMAINING_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_RANGE_READ = "android.car.permission.oem.POWERTRAIN_RANGE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_TIME_REMAINING_READ = "android.car.permission.oem.POWERTRAIN_TIME_REMAINING_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_POWERTRAIN_TYPE_READ = "android.car.permission.oem.POWERTRAIN_TYPE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_ROOF_LOAD_READ = "android.car.permission.oem.ROOF_LOAD_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_SPEED_READ = "android.car.permission.oem.SPEED_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_START_TIME_READ = "android.car.permission.oem.START_TIME_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_TRAILER_IS_CONNECTED_READ = "android.car.permission.oem.TRAILER_IS_CONNECTED_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_TRAVELED_DISTANCE_READ = "android.car.permission.oem.TRAVELED_DISTANCE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_TRAVELED_DISTANCE_SINCE_START_READ = "android.car.permission.oem.TRAVELED_DISTANCE_SINCE_START_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_TRIP_DURATION_READ = "android.car.permission.oem.TRIP_DURATION_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_TRIP_METER_READING_READ = "android.car.permission.oem.TRIP_METER_READING_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_TRIP_METER_READING_WRITE = "android.car.permission.oem.TRIP_METER_READING_WRITE";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_TURNING_DIAMETER_READ = "android.car.permission.oem.TURNING_DIAMETER_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_BODY_TYPE_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_BODY_TYPE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_BRAND_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_BRAND_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_DATE_VEHICLE_FIRST_REGISTERED_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_DATE_VEHICLE_FIRST_REGISTERED_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_LICENSE_PLATE_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_LICENSE_PLATE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_MEETS_EMISSION_STANDARD_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_MEETS_EMISSION_STANDARD_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_MODEL_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_MODEL_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_PRODUCTION_DATE_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_PRODUCTION_DATE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_VEHICLE_EXTERIOR_COLOR_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_VEHICLE_EXTERIOR_COLOR_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_VEHICLE_MODEL_DATE_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_VEHICLE_MODEL_DATE_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_VEHICLE_SEATING_CAPACITY_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_VEHICLE_SEATING_CAPACITY_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_VIN_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_VIN_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_WMI_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_WMI_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_VEHICLE_IDENTIFICATION_YEAR_READ = "android.car.permission.oem.VEHICLE_IDENTIFICATION_YEAR_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_WIDTH_EXCLUDING_MIRRORS_READ = "android.car.permission.oem.WIDTH_EXCLUDING_MIRRORS_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_WIDTH_FOLDED_MIRRORS_READ = "android.car.permission.oem.WIDTH_FOLDED_MIRRORS_READ";

	@FlaggedApi(FLAG_OEM_VEHICLE_PROPERTY)
	public static final String PERMISSION_OEM_WIDTH_INCLUDING_MIRRORS_READ = "android.car.permission.oem.WIDTH_INCLUDING_MIRRORS_READ";

}