public final class VssPermissions {

	public static final String PERMISSION_VSS_AVERAGE_SPEED_READ = "android.car.permission.VSS_AVERAGE_SPEED_READ";

	public static final String PERMISSION_VSS_CARGO_VOLUME_READ = "android.car.permission.VSS_CARGO_VOLUME_READ";

	public static final String PERMISSION_VSS_CURB_WEIGHT_READ = "android.car.permission.VSS_CURB_WEIGHT_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_ALTITUDE_READ = "android.car.permission.VSS_CURRENT_LOCATION_ALTITUDE_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_GNSSRECEIVER_FIX_TYPE_READ = "android.car.permission.VSS_CURRENT_LOCATION_GNSSRECEIVER_FIX_TYPE_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_X_READ = "android.car.permission.VSS_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_X_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Y_READ = "android.car.permission.VSS_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Y_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Z_READ = "android.car.permission.VSS_CURRENT_LOCATION_GNSSRECEIVER_MOUNTING_POSITION_Z_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_HEADING_READ = "android.car.permission.VSS_CURRENT_LOCATION_HEADING_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_HORIZONTAL_ACCURACY_READ = "android.car.permission.VSS_CURRENT_LOCATION_HORIZONTAL_ACCURACY_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_LATITUDE_READ = "android.car.permission.VSS_CURRENT_LOCATION_LATITUDE_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_LONGITUDE_READ = "android.car.permission.VSS_CURRENT_LOCATION_LONGITUDE_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_TIMESTAMP_READ = "android.car.permission.VSS_CURRENT_LOCATION_TIMESTAMP_READ";

	public static final String PERMISSION_VSS_CURRENT_LOCATION_VERTICAL_ACCURACY_READ = "android.car.permission.VSS_CURRENT_LOCATION_VERTICAL_ACCURACY_READ";

	public static final String PERMISSION_VSS_CURRENT_OVERALL_WEIGHT_READ = "android.car.permission.VSS_CURRENT_OVERALL_WEIGHT_READ";

	public static final String PERMISSION_VSS_EMISSIONS_CO2_READ = "android.car.permission.VSS_EMISSIONS_CO2_READ";

	public static final String PERMISSION_VSS_GROSS_WEIGHT_READ = "android.car.permission.VSS_GROSS_WEIGHT_READ";

	public static final String PERMISSION_VSS_HEIGHT_READ = "android.car.permission.VSS_HEIGHT_READ";

	public static final String PERMISSION_VSS_IS_BROKEN_DOWN_READ = "android.car.permission.VSS_IS_BROKEN_DOWN_READ";

	public static final String PERMISSION_VSS_IS_MOVING_READ = "android.car.permission.VSS_IS_MOVING_READ";

	public static final String PERMISSION_VSS_LENGTH_READ = "android.car.permission.VSS_LENGTH_READ";

	public static final String PERMISSION_VSS_LOW_VOLTAGE_SYSTEM_STATE_READ = "android.car.permission.VSS_LOW_VOLTAGE_SYSTEM_STATE_READ";

	public static final String PERMISSION_VSS_MAX_TOW_BALL_WEIGHT_READ = "android.car.permission.VSS_MAX_TOW_BALL_WEIGHT_READ";

	public static final String PERMISSION_VSS_MAX_TOW_WEIGHT_READ = "android.car.permission.VSS_MAX_TOW_WEIGHT_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_ACCUMULATED_BRAKING_ENERGY_READ = "android.car.permission.VSS_POWERTRAIN_ACCUMULATED_BRAKING_ENERGY_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_LEVEL_READ = "android.car.permission.VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_LEVEL_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_TEMPERATURE_READ = "android.car.permission.VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_COOLANT_TEMPERATURE_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_CAPACITY_READ = "android.car.permission.VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_CAPACITY_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_LEVEL_READ = "android.car.permission.VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_LEVEL_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_TEMPERATURE_READ = "android.car.permission.VSS_POWERTRAIN_COMBUSTION_ENGINE_ENGINE_OIL_TEMPERATURE_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_COMBUSTION_ENGINE_IS_RUNNING_READ = "android.car.permission.VSS_POWERTRAIN_COMBUSTION_ENGINE_IS_RUNNING_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_COMBUSTION_ENGINE_SPEED_READ = "android.car.permission.VSS_POWERTRAIN_COMBUSTION_ENGINE_SPEED_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_ABSOLUTE_LEVEL_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_ABSOLUTE_LEVEL_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_AVERAGE_CONSUMPTION_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_AVERAGE_CONSUMPTION_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_LAST_REFUEL_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_LAST_REFUEL_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_START_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_CONSUMPTION_SINCE_START_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_HYBRID_TYPE_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_HYBRID_TYPE_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_INSTANT_CONSUMPTION_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_INSTANT_CONSUMPTION_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_IS_ENGINE_STOP_START_ENABLED_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_IS_ENGINE_STOP_START_ENABLED_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_LEVEL_LOW_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_LEVEL_LOW_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_WRITE = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_IS_FUEL_PORT_FLAP_OPEN_WRITE";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_RANGE_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_RANGE_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_REFUEL_PORT_POSITION_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_REFUEL_PORT_POSITION_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_RELATIVE_LEVEL_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_RELATIVE_LEVEL_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_TYPES_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_SUPPORTED_FUEL_TYPES_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_TANK_CAPACITY_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_TANK_CAPACITY_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_FUEL_SYSTEM_TIME_REMAINING_READ = "android.car.permission.VSS_POWERTRAIN_FUEL_SYSTEM_TIME_REMAINING_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_RANGE_READ = "android.car.permission.VSS_POWERTRAIN_RANGE_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_TIME_REMAINING_READ = "android.car.permission.VSS_POWERTRAIN_TIME_REMAINING_READ";

	public static final String PERMISSION_VSS_POWERTRAIN_TYPE_READ = "android.car.permission.VSS_POWERTRAIN_TYPE_READ";

	public static final String PERMISSION_VSS_ROOF_LOAD_READ = "android.car.permission.VSS_ROOF_LOAD_READ";

	public static final String PERMISSION_VSS_SPEED_READ = "android.car.permission.VSS_SPEED_READ";

	public static final String PERMISSION_VSS_START_TIME_READ = "android.car.permission.VSS_START_TIME_READ";

	public static final String PERMISSION_VSS_TRAILER_IS_CONNECTED_READ = "android.car.permission.VSS_TRAILER_IS_CONNECTED_READ";

	public static final String PERMISSION_VSS_TRAVELED_DISTANCE_READ = "android.car.permission.VSS_TRAVELED_DISTANCE_READ";

	public static final String PERMISSION_VSS_TRAVELED_DISTANCE_SINCE_START_READ = "android.car.permission.VSS_TRAVELED_DISTANCE_SINCE_START_READ";

	public static final String PERMISSION_VSS_TRIP_DURATION_READ = "android.car.permission.VSS_TRIP_DURATION_READ";

	public static final String PERMISSION_VSS_TRIP_METER_READING_READ = "android.car.permission.VSS_TRIP_METER_READING_READ";

	public static final String PERMISSION_VSS_TRIP_METER_READING_WRITE = "android.car.permission.VSS_TRIP_METER_READING_WRITE";

	public static final String PERMISSION_VSS_TURNING_DIAMETER_READ = "android.car.permission.VSS_TURNING_DIAMETER_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_BODY_TYPE_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_BODY_TYPE_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_BRAND_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_BRAND_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_DATE_VEHICLE_FIRST_REGISTERED_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_DATE_VEHICLE_FIRST_REGISTERED_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_LICENSE_PLATE_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_LICENSE_PLATE_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_MEETS_EMISSION_STANDARD_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_MEETS_EMISSION_STANDARD_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_MODEL_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_MODEL_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_PRODUCTION_DATE_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_PRODUCTION_DATE_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_VEHICLE_EXTERIOR_COLOR_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_VEHICLE_EXTERIOR_COLOR_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_VEHICLE_MODEL_DATE_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_VEHICLE_MODEL_DATE_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_VEHICLE_SEATING_CAPACITY_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_VEHICLE_SEATING_CAPACITY_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_WMI_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_WMI_READ";

	public static final String PERMISSION_VSS_VEHICLE_IDENTIFICATION_YEAR_READ = "android.car.permission.VSS_VEHICLE_IDENTIFICATION_YEAR_READ";

	public static final String PERMISSION_VSS_WIDTH_EXCLUDING_MIRRORS_READ = "android.car.permission.VSS_WIDTH_EXCLUDING_MIRRORS_READ";

	public static final String PERMISSION_VSS_WIDTH_FOLDED_MIRRORS_READ = "android.car.permission.VSS_WIDTH_FOLDED_MIRRORS_READ";

	public static final String PERMISSION_VSS_WIDTH_INCLUDING_MIRRORS_READ = "android.car.permission.VSS_WIDTH_INCLUDING_MIRRORS_READ";
}