class A {

	' sensor: This is the first signal.
	' unit: km
	signalA : int8
	aA : PAA.AA
}
' Branch A.AA.
package PAA {
	class AA {

		' sensor: This is yet another signal.
		' unit: km
		signalAA : int8
	}
}
