class AIS {
	b : PB.BIS0
	y : PY.Y
	y1 : A
	y2 : A
}
' This description will be duplicated.
package PB {
	class BIS0 {
		row1 : PB.B_IS1
		row2 : PB.B_IS1
	}
	class B_IS1 {
		left : PB.B
		right : PB.B
	}
	class B {

		' sensor: This description will also exist multiple times.
		' unit: km
		c : int8
	}
}
' d
package PY {
	class Y {

		' attribute: d
		count : uint8
	}
}
class A {
	z : PZ.ZIS
}
' d
package PZ {
	class ZIS {

		' branch: d
		z1 : None

		' branch: d
		z2 : None
	}
}
